# https://hub.docker.com/r/linuxserver/duplicati
---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - CLI_ARGS= #optional
    volumes:
      - /mnt/volumes/config:/config
      - /backups:/backups
      - /:/source
    ports:
      - 8200:8200
    restart: unless-stopped
